version: 2.1

orbs:
  haskell: haskell-works/haskell-build@2.0.2
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@1.0.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-cci-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci